//! Zig Code Generator for CatLang

use crate::ast::*;

/// Code generation error types
#[derive(Debug, Clone)]
pub struct CodeGenError {
    pub message: String,
}

impl std::fmt::Display for CodeGenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Code generation error: {}", self.message)
    }
}

pub type CodeGenResult<T> = Result<T, CodeGenError>;

/// Zig code generator
pub struct ZigCodeGen {
    output: String,
    indent_level: usize,
    mutated_vars: std::collections::HashSet<String>, // Variables that are reassigned
}

impl ZigCodeGen {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent_level: 0,
            mutated_vars: std::collections::HashSet::new(),
        }
    }

    pub fn generate(mut self, program: &Program) -> CodeGenResult<String> {
        // Generate Zig header
        self.writeln("// Generated by CatLang Compiler");
        self.writeln("const std = @import(\"std\");");
        self.writeln("");

        // Generate optimized print helper
        self.writeln("// Print helper - converts CatLang format {var} to Zig format {}");
        self.writeln("inline fn print(comptime fmt: []const u8, args: anytype) void {");
        self.indent_level += 1;
        self.writeln("std.debug.print(fmt, args);");
        self.indent_level -= 1;
        self.writeln("}");
        self.writeln("");

        // Generate readInput helper - reads a line from stdin with optional prompt
        self.writeln("// readInput - reads a line from stdin with optional prompt");
        self.writeln("fn readInput() []const u8 {");
        self.indent_level += 1;
        self.writeln("const stdin = std.io.getStdIn().reader();");
        self.writeln("const stdout = std.io.getStdOut().writer();");
        self.writeln("var buffer: [1024]u8 = undefined;");
        self.writeln("const line = stdin.readUntilDelimiter(&buffer, '\\n') catch &buffer;");
        self.writeln("return line;");
        self.indent_level -= 1;
        self.writeln("}");
        self.writeln("");

        self.writeln("// readInputWithPrompt - prints prompt then reads a line from stdin");
        self.writeln("fn readInputWithPrompt(comptime fmt: []const u8, args: anytype) []const u8 {");
        self.indent_level += 1;
        self.writeln("const stdin = std.io.getStdIn().reader();");
        self.writeln("const stdout = std.io.getStdOut().writer();");
        self.writeln("print(fmt, args);");
        self.writeln("var buffer: [1024]u8 = undefined;");
        self.writeln("const line = stdin.readUntilDelimiter(&buffer, '\\n') catch &buffer;");
        self.writeln("return line;");
        self.indent_level -= 1;
        self.writeln("}");
        self.writeln("");

        // Generate readInputTo - reads input and converts to target type
        self.writeln("// readInputTo - prints prompt, reads input, and converts to target type");
        self.writeln("fn readInputTo(comptime fmt: []const u8, args: anytype, comptime T: type) T {");
        self.indent_level += 1;
        self.writeln("const stdin = std.io.getStdIn().reader();");
        self.writeln("const stdout = std.io.getStdOut().writer();");
        self.writeln("print(fmt, args);");
        self.writeln("var buffer: [1024]u8 = undefined;");
        self.writeln("const line = stdin.readUntilDelimiter(&buffer, '\\n') catch &buffer;");
        self.writeln("if (T == []const u8) {");
        self.indent_level += 1;
        self.writeln("return line;");
        self.indent_level -= 1;
        self.writeln("} else if (T == i32) {");
        self.indent_level += 1;
        self.writeln("return std.fmt.parseInt(i32, line, 10) catch 0;");
        self.indent_level -= 1;
        self.writeln("} else if (T == i64) {");
        self.indent_level += 1;
        self.writeln("return std.fmt.parseInt(i64, line, 10) catch 0;");
        self.indent_level -= 1;
        self.writeln("} else if (T == f64) {");
        self.indent_level += 1;
        self.writeln("return std.fmt.parseFloat(f64, line) catch 0.0;");
        self.indent_level -= 1;
        self.writeln("} else if (T == i128) {");
        self.indent_level += 1;
        self.writeln("return std.fmt.parseInt(i128, line, 10) catch 0;");
        self.indent_level -= 1;
        self.writeln("} else if (T == f128) {");
        self.indent_level += 1;
        self.writeln("return std.fmt.parseFloat(f128, line) catch 0.0;");
        self.indent_level -= 1;
        self.writeln("} else {");
        self.indent_level += 1;
        self.writeln("return line;");
        self.indent_level -= 1;
        self.writeln("}");
        self.indent_level -= 1;
        self.writeln("}");
        self.writeln("");

        // Generate Timer helper struct
        self.writeln("// Timer - High precision timer");
        self.writeln("const Timer = struct {");
        self.indent_level += 1;
        self.writeln("start_time: i64,");
        self.writeln("end_time: i64,");
        self.writeln("running: bool,");
        self.writeln("");
        self.writeln("fn init() Timer {");
        self.indent_level += 1;
        self.writeln("return Timer { .start_time = 0, .end_time = 0, .running = false };");
        self.indent_level -= 1;
        self.writeln("}");
        self.writeln("");
        self.writeln("inline fn start(self: *Timer) void {");
        self.indent_level += 1;
        self.writeln("self.start_time = @as(i64, @intCast(std.time.nanoTimestamp()));");
        self.writeln("self.running = true;");
        self.indent_level -= 1;
        self.writeln("}");
        self.writeln("");
        self.writeln("inline fn stop(self: *Timer) void {");
        self.indent_level += 1;
        self.writeln("self.end_time = @as(i64, @intCast(std.time.nanoTimestamp()));");
        self.writeln("self.running = false;");
        self.indent_level -= 1;
        self.writeln("}");
        self.writeln("");
        self.writeln("inline fn elapsedNs(self: *Timer) i64 {");
        self.indent_level += 1;
        self.writeln("var end = self.end_time;");
        self.writeln("if (self.running) {");
        self.indent_level += 1;
        self.writeln("end = @as(i64, @intCast(std.time.nanoTimestamp()));");
        self.indent_level -= 1;
        self.writeln("}");
        self.writeln("return end - self.start_time;");
        self.indent_level -= 1;
        self.writeln("}");
        self.writeln("");
        self.writeln("inline fn ms(self: *Timer) f64 {");
        self.indent_level += 1;
        self.writeln("return @as(f64, @floatFromInt(self.elapsedNs())) / 1_000_000.0;");
        self.indent_level -= 1;
        self.writeln("}");
        self.writeln("");
        self.writeln("inline fn seconds(self: *Timer) f64 {");
        self.indent_level += 1;
        self.writeln("return @as(f64, @floatFromInt(self.elapsedNs())) / 1_000_000_000.0;");
        self.indent_level -= 1;
        self.writeln("}");
        self.writeln("");
        self.writeln("inline fn us(self: *Timer) f64 {");
        self.indent_level += 1;
        self.writeln("return @as(f64, @floatFromInt(self.elapsedNs())) / 1_000.0;");
        self.indent_level -= 1;
        self.writeln("}");
        self.indent_level -= 1;
        self.writeln("};");
        self.writeln("");

        // First pass: collect top-level statements and analyze mutations
        let mut top_level_statements: Vec<&Block> = Vec::new();
        let mut mutated_vars: std::collections::HashSet<String> = std::collections::HashSet::new();

        // Helper function to collect mutated variables from a block (including nested blocks)
        fn collect_mutations(block: &Block, mutated_vars: &mut std::collections::HashSet<String>) {
            for stmt in &block.statements {
                match stmt {
                    Stmt::Assignment(assignment) => {
                        if let AssignmentTarget::Identifier(name) = &assignment.target {
                            mutated_vars.insert(name.clone());
                        }
                    }
                    Stmt::If(if_stmt) => {
                        collect_mutations(&if_stmt.then_block, mutated_vars);
                        if let Some(else_branch) = &if_stmt.else_branch {
                            match else_branch {
                                ElseBranch::Block(block) => collect_mutations(block, mutated_vars),
                                ElseBranch::ElseIf(if_stmt) => {
                                    collect_mutations(&if_stmt.then_block, mutated_vars);
                                }
                            }
                        }
                    }
                    Stmt::While(while_stmt) => {
                        collect_mutations(&while_stmt.body, mutated_vars);
                    }
                    Stmt::For(for_stmt) => {
                        collect_mutations(&for_stmt.body, mutated_vars);
                    }
                    Stmt::Block(block) => {
                        collect_mutations(block, mutated_vars);
                    }
                    Stmt::UnsafeBlock(unsafe_block) => {
                        collect_mutations(&unsafe_block.body, mutated_vars);
                    }
                    Stmt::Try(try_stmt) => {
                        collect_mutations(&try_stmt.try_block, mutated_vars);
                        for catch_clause in &try_stmt.catch_clauses {
                            collect_mutations(&catch_clause.body, mutated_vars);
                        }
                    }
                    _ => {}
                }
            }
        }

        // Process declarations (excluding top-level statements for now)
        for decl in &program.declarations {
            match decl {
                TopLevelDecl::Statements(block) => {
                    top_level_statements.push(block);
                    // Collect mutated variables (including nested blocks)
                    collect_mutations(block, &mut mutated_vars);
                }
                _ => {
                    self.generate_top_level_decl(decl)?;
                }
            }
        }

        // Generate main function if there are top-level statements
        if !top_level_statements.is_empty() {
            self.writeln("pub fn main() void {");
            self.indent_level += 1;

            // Store mutated vars for variable declaration
            self.mutated_vars = mutated_vars;

            for block in top_level_statements {
                for stmt in &block.statements {
                    self.generate_statement(stmt)?;
                }
            }

            self.indent_level -= 1;
            self.writeln("}");
        }

        Ok(self.output)
    }

    fn generate_top_level_decl(&mut self, decl: &TopLevelDecl) -> CodeGenResult<()> {
        match decl {
            TopLevelDecl::Import(import_stmt) => {
                // Third-party imports - generate Zig import
                self.generate_import(import_stmt)?;
            }
            TopLevelDecl::Struct(struct_def) => {
                self.generate_struct(struct_def)?;
            }
            TopLevelDecl::Impl(impl_def) => {
                self.generate_impl(impl_def)?;
            }
            TopLevelDecl::Function(fn_def) => {
                self.generate_function(fn_def, false)?;
            }
            TopLevelDecl::AsyncFunction(fn_def) => {
                self.generate_function(fn_def, true)?;
            }
            TopLevelDecl::GlobalVar(global_var) => {
                self.generate_global_var(global_var)?;
            }
            TopLevelDecl::Statements(_) => {
                // Already handled in generate() - skip here
            }
        }
        Ok(())
    }

    fn generate_import(&mut self, import: &ImportStmt) -> CodeGenResult<()> {
        match import {
            ImportStmt::Simple {
                module_path, alias, ..
            } => {
                let module_name = module_path.join(".");
                let zig_module = module_name.replace(".", "/");
                if let Some(a) = alias {
                    self.writeln(&format!("const {} = @import(\"{}\");", a, zig_module));
                } else {
                    let name = module_path.last().unwrap();
                    self.writeln(&format!("const {} = @import(\"{}\");", name, zig_module));
                }
            }
            ImportStmt::From {
                module_path, names, ..
            } => {
                let zig_module = module_path.join("/");
                for (name, alias) in names {
                    let zig_name = alias.as_ref().unwrap_or(name);
                    self.writeln(&format!(
                        "const {} = @import(\"{}\").{};",
                        zig_name, zig_module, name
                    ));
                }
            }
        }
        Ok(())
    }

    fn generate_struct(&mut self, struct_def: &StructDef) -> CodeGenResult<()> {
        self.writeln(&format!("const {} = struct {{", struct_def.name));
        self.indent_level += 1;

        for field in &struct_def.fields {
            let zig_type = field.field_type.to_zig_type();
            // Zig fields need default values or must be optional
            self.writeln(&format!("{}: {},", field.name, zig_type));
        }

        self.indent_level -= 1;
        self.writeln("};");
        self.writeln("");
        Ok(())
    }

    fn generate_impl(&mut self, impl_def: &ImplDef) -> CodeGenResult<()> {
        // In Zig, methods are typically added to structs directly
        // We'll generate them as namespaced functions
        for method in &impl_def.methods {
            self.generate_function(method, method.is_async)?;
        }
        Ok(())
    }

    fn generate_function(&mut self, fn_def: &FunctionDef, is_async: bool) -> CodeGenResult<()> {
        let return_type = if let Some(rt) = &fn_def.return_type {
            rt.to_zig_type()
        } else {
            "void".to_string()
        };

        // Use "main" for the entry point function (Zig requires lowercase and pub)
        // Case-insensitive check for Main/main
        let is_main = fn_def.name.eq_ignore_ascii_case("main");
        let func_name = if is_main { "main" } else { &fn_def.name };
        let pub_prefix = if is_main { "pub " } else { "" };

        let async_prefix = if is_async { "async " } else { "" };

        self.writeln(&format!(
            "{}fn {}({}) {}{return_type} {{",
            pub_prefix,
            func_name,
            self.format_params(&fn_def.params),
            async_prefix,
            return_type = return_type
        ));
        self.indent_level += 1;

        // Generate function body
        let mut last_was_return = false;
        for stmt in &fn_def.body.statements {
            self.generate_statement(stmt)?;
            if matches!(stmt, Stmt::Return(_)) {
                last_was_return = true;
            }
        }

        // Add return for void functions only if last statement wasn't a return
        if return_type == "void" && !last_was_return {
            self.writeln("return;");
        }

        self.indent_level -= 1;
        self.writeln("}");
        self.writeln("");
        Ok(())
    }

    fn format_params(&self, params: &[Param]) -> String {
        if params.is_empty() {
            return String::new();
        }

        let mut result = String::new();
        for (i, param) in params.iter().enumerate() {
            if i > 0 {
                result.push_str(", ");
            }
            let zig_type = param.param_type.to_zig_type();
            result.push_str(&format!("{}: {}", param.name, zig_type));
        }
        result
    }

    fn generate_global_var(&mut self, global_var: &GlobalVarDecl) -> CodeGenResult<()> {
        let zig_type = global_var.var_type.to_zig_type();

        if let Some(init) = &global_var.init {
            let init_expr = self.generate_expr(init)?;
            self.writeln(&format!(
                "const {}: {} = {}
                ;",
                global_var.name, zig_type, init_expr
            ));
        } else {
            self.writeln(&format!(
                "var {}: {} = undefined;",
                global_var.name, zig_type
            ));
        }
        Ok(())
    }

    fn generate_statement(&mut self, stmt: &Stmt) -> CodeGenResult<()> {
        match stmt {
            Stmt::VarDecl(var_decl) => self.generate_var_decl(var_decl)?,
            Stmt::Assignment(assignment) => self.generate_assignment(assignment)?,
            Stmt::CopyStmt(copy_stmt) => self.generate_copy_stmt(copy_stmt)?,
            Stmt::If(if_stmt) => self.generate_if(if_stmt)?,
            Stmt::While(while_stmt) => self.generate_while(while_stmt)?,
            Stmt::For(for_stmt) => self.generate_for(for_stmt)?,
            Stmt::Switch(switch_stmt) => self.generate_switch(switch_stmt)?,
            Stmt::Try(try_stmt) => self.generate_try(try_stmt)?,
            Stmt::Throw(throw_stmt) => self.generate_throw(throw_stmt)?,
            Stmt::AsyncStmt(async_stmt) => self.generate_async_stmt(async_stmt)?,
            Stmt::Block(block) => self.generate_block(block)?,
            Stmt::UnsafeBlock(unsafe_block) => self.generate_unsafe_block(unsafe_block)?,
            Stmt::Expr(expr) => {
                // Check if this is an input() call with variable argument
                // If so, generate assignment instead of expression statement
                if let ExprKind::Call(func, args) = &expr.kind {
                    if let ExprKind::Identifier(func_name) = &func.kind {
                        if func_name == "input" && !args.is_empty() {
                            // Check if last argument is a variable (for type conversion pattern)
                            let last_arg = args.last().unwrap();
                            if let ExprKind::Identifier(var_name) = &last_arg.kind {
                                // Check if first arg is a string literal (format string)
                                let is_format_string = matches!(&args[0].kind, ExprKind::Literal(Literal::String(_) | Literal::InterpolatedString(_)));
                                if is_format_string {
                                    // This is input("prompt", var) pattern - generate assignment
                                    let expr_str = self.generate_expr(expr)?;
                                    self.writeln(&format!("{} = {};", var_name, expr_str));
                                    return Ok(());
                                }
                            }
                        }
                    }
                }
                let expr_str = self.generate_expr(expr)?;
                self.writeln(&format!("{};", expr_str));
            }
            Stmt::Return(return_stmt) => self.generate_return(return_stmt)?,
        }
        Ok(())
    }

    fn generate_var_decl(&mut self, var_decl: &VarDecl) -> CodeGenResult<()> {
        // Use 'var' for Timer types (methods need mutable reference) or if the variable is reassigned
        // This is required by Zig's strict const checking
        let is_timer = matches!(var_decl.var_type, TypeExpr::Timer);
        let var_keyword = if is_timer || self.mutated_vars.contains(&var_decl.name) {
            "var"
        } else {
            "const"
        };

        if let Some(init) = &var_decl.init {
            let init_expr = self.generate_expr(init)?;
            // For variables named "_", discard the value

            if var_decl.name == "_" || var_decl.name.starts_with("_") {
                self.writeln(&format!("_ = {};", init_expr));
            } else {
                // Handle type inference ("auto" type)
                if var_decl.var_type.to_zig_type() == "auto" {
                    // Let Zig infer the type using @TypeOf
                    self.writeln(&format!(
                        "{} {} = @TypeOf({});",
                        var_keyword, var_decl.name, init_expr
                    ));
                } else {
                    let zig_type = var_decl.var_type.to_zig_type();
                    self.writeln(&format!(
                        "{} {}: {} = {};",
                        var_keyword, var_decl.name, zig_type, init_expr
                    ));
                }
            }
        } else {
            let zig_type = var_decl.var_type.to_zig_type();
            self.writeln(&format!("var {}: {} = undefined;", var_decl.name, zig_type));
        }
        Ok(())
    }

    fn generate_assignment(&mut self, assignment: &Assignment) -> CodeGenResult<()> {
        let op_str = match assignment.op {
            AssignOp::Equal => "=",
            AssignOp::PlusEqual => "+=",
            AssignOp::MinusEqual => "-=",
            AssignOp::StarEqual => "*=",
            AssignOp::SlashEqual => "/=",
            AssignOp::PercentEqual => "%=",
            AssignOp::AndEqual => "&=",
            AssignOp::OrEqual => "|=",
            AssignOp::XorEqual => "^=",
        };

        let value_expr = self.generate_expr(&assignment.value)?;
        let target_str = assignment.target.to_zig();
        self.writeln(&format!("{} {} {};", target_str, op_str, value_expr));
        Ok(())
    }

    fn generate_copy_stmt(&mut self, copy_stmt: &CopyStmt) -> CodeGenResult<()> {
        // cpy dest(bytes) - memory copy operation
        let size_type = copy_stmt.size_type.to_zig_type();
        self.writeln(&format!(
            "// cpy {}({}) - memory copy",
            copy_stmt.dest, size_type
        ));
        self.writeln(&format!(
            "@memcpy(@as([*]u8, @ptrFromInt(@intFromPtr(&{}))), @as([*]const u8, @ptrFromInt(@intFromPtr(&{}))), {});",
            copy_stmt.dest, copy_stmt.dest, size_type
        ));
        Ok(())
    }

    fn generate_if(&mut self, if_stmt: &IfStmt) -> CodeGenResult<()> {
        let condition = self.generate_expr(&if_stmt.condition)?;
        self.writeln(&format!("if ({}) {{", condition));
        self.indent_level += 1;

        for stmt in &if_stmt.then_block.statements {
            self.generate_statement(stmt)?;
        }

        self.indent_level -= 1;

        if let Some(else_branch) = &if_stmt.else_branch {
            match else_branch {
                ElseBranch::Block(block) => {
                    self.writeln("} else {");
                    self.indent_level += 1;
                    for stmt in &block.statements {
                        self.generate_statement(stmt)?;
                    }
                    self.indent_level -= 1;
                }
                ElseBranch::ElseIf(if_stmt) => {
                    let condition = self.generate_expr(&if_stmt.condition)?;
                    self.writeln(&format!("}} else if ({}) {{", condition));
                    self.indent_level += 1;
                    for stmt in &if_stmt.then_block.statements {
                        self.generate_statement(stmt)?;
                    }
                    self.indent_level -= 1;

                    // Handle nested else
                    if let Some(nested_else) = &if_stmt.else_branch {
                        match nested_else {
                            ElseBranch::Block(block) => {
                                self.writeln("} else {");
                                self.indent_level += 1;
                                for stmt in &block.statements {
                                    self.generate_statement(stmt)?;
                                }
                                self.indent_level -= 1;
                            }
                            ElseBranch::ElseIf(_) => {
                                // Recursively handle
                            }
                        }
                    }
                }
            }
        }

        self.writeln("}");
        Ok(())
    }

    fn generate_while(&mut self, while_stmt: &WhileStmt) -> CodeGenResult<()> {
        let condition = self.generate_expr(&while_stmt.condition)?;
        self.writeln(&format!("while ({}) {{", condition));
        self.indent_level += 1;

        for stmt in &while_stmt.body.statements {
            self.generate_statement(stmt)?;
        }

        self.indent_level -= 1;
        self.writeln("}");
        Ok(())
    }

    fn generate_for(&mut self, for_stmt: &ForStmt) -> CodeGenResult<()> {
        // for (new i = 0, i < n, i = i + 1) [...]
        // Convert to Zig while loop

        // Generate init
        self.generate_var_decl(&for_stmt.init)?;

        let condition = self.generate_expr(&for_stmt.condition)?;
        self.writeln(&format!("while ({}) {{", condition));
        self.indent_level += 1;

        for stmt in &for_stmt.body.statements {
            self.generate_statement(stmt)?;
        }

        // Generate update
        let update_target = for_stmt.update.target.to_zig();
        let update_op = for_stmt.update.op;
        let update_value = self.generate_expr(&for_stmt.update.value)?;

        let op_str = match update_op {
            AssignOp::Equal => "=",
            AssignOp::PlusEqual => "+=",
            AssignOp::MinusEqual => "-=",
            AssignOp::StarEqual => "*=",
            AssignOp::SlashEqual => "/=",
            AssignOp::PercentEqual => "%=",
            AssignOp::AndEqual => "&=",
            AssignOp::OrEqual => "|=",
            AssignOp::XorEqual => "^=",
        };
        self.writeln(&format!("{} {} {};", update_target, op_str, update_value));

        self.indent_level -= 1;
        self.writeln("}");
        Ok(())
    }

    fn generate_switch(&mut self, switch_stmt: &SwitchStmt) -> CodeGenResult<()> {
        let expr = self.generate_expr(&switch_stmt.expr)?;
        self.writeln(&format!("switch ({}) {{", expr));
        self.indent_level += 1;

        for case in &switch_stmt.cases {
            match &case.pattern {
                Pattern::Literal(lit) => {
                    let pattern = self.generate_literal(lit)?;
                    self.writeln(&format!("{} => {{", pattern));
                }
                Pattern::Identifier(name) => {
                    self.writeln(&format!("{} => {{", name));
                }
                Pattern::Underscore => {
                    self.writeln("else => {");
                }
            }
            self.indent_level += 1;
            for stmt in &case.body.statements {
                self.generate_statement(stmt)?;
            }
            self.indent_level -= 1;
            self.writeln("},");
        }

        self.indent_level -= 1;
        self.writeln("}");
        Ok(())
    }

    fn generate_try(&mut self, try_stmt: &TryStmt) -> CodeGenResult<()> {
        // Zig error handling uses error unions
        self.writeln("errdefer {}");
        self.writeln("{");
        self.indent_level += 1;

        for stmt in &try_stmt.try_block.statements {
            self.generate_statement(stmt)?;
        }

        self.indent_level -= 1;
        self.writeln("}");

        // Generate catch blocks
        for catch_clause in &try_stmt.catch_clauses {
            // In Zig, this would be handled differently
            self.writeln(&format!(
                "// catch ({}: {}) - error handling",
                catch_clause.var_name,
                catch_clause.error_type.to_zig_type()
            ));
        }

        Ok(())
    }

    fn generate_throw(&mut self, throw_stmt: &ThrowStmt) -> CodeGenResult<()> {
        let expr = self.generate_expr(&throw_stmt.expr)?;
        self.writeln(&format!("return {};", expr));
        Ok(())
    }

    fn generate_async_stmt(&mut self, async_stmt: &AsyncStmt) -> CodeGenResult<()> {
        match async_stmt {
            AsyncStmt::Await(expr) => {
                let expr_str = self.generate_expr(expr)?;
                self.writeln(&format!("await {};", expr_str));
            }
            AsyncStmt::Spawn(expr) => {
                let expr_str = self.generate_expr(expr)?;
                self.writeln(&format!("const _ = async {};", expr_str));
            }
        }
        Ok(())
    }

    fn generate_block(&mut self, block: &Block) -> CodeGenResult<()> {
        self.writeln("{");
        self.indent_level += 1;

        for stmt in &block.statements {
            self.generate_statement(stmt)?;
        }

        self.indent_level -= 1;
        self.writeln("}");
        Ok(())
    }

    fn generate_unsafe_block(&mut self, unsafe_block: &UnsafeBlock) -> CodeGenResult<()> {
        // Generate comment about unsafe
        let modifier_str = match &unsafe_block.scope_modifier {
            ScopeModifier::Close(target) => format!("close({})", self.safety_target_str(target)),
            ScopeModifier::Keep(target) => format!("keep({})", self.safety_target_str(target)),
            ScopeModifier::All => "all".to_string(),
        };
        self.writeln(&format!("// unsafe {} {{", modifier_str));
        self.generate_block(&unsafe_block.body)?;
        Ok(())
    }

    fn safety_target_str(&self, target: &SafetyTarget) -> String {
        match target {
            SafetyTarget::Init => "init".to_string(),
            SafetyTarget::Bounds => "bounds".to_string(),
            SafetyTarget::Lifetime => "lifetime".to_string(),
            SafetyTarget::Null => "null".to_string(),
            SafetyTarget::Identifier(name) => name.clone(),
        }
    }

    fn generate_return(&mut self, return_stmt: &ReturnStmt) -> CodeGenResult<()> {
        if let Some(expr) = &return_stmt.expr {
            let expr_str = self.generate_expr(expr)?;
            self.writeln(&format!("return {};", expr_str));
        } else {
            self.writeln("return;");
        }
        Ok(())
    }

    fn generate_expr(&mut self, expr: &Expr) -> CodeGenResult<String> {
        match &expr.kind {
            ExprKind::Literal(lit) => self.generate_literal(lit),
            ExprKind::Identifier(name) => Ok(name.clone()),
            ExprKind::Binary(left, op, right) => {
                let left_str = self.generate_expr(left)?;
                let right_str = self.generate_expr(right)?;
                let op_str = match op {
                    BinaryOp::Add => "+",
                    BinaryOp::Sub => "-",
                    BinaryOp::Mul => "*",
                    BinaryOp::Div => "/",
                    BinaryOp::Rem => "%",
                    BinaryOp::Eq => "==",
                    BinaryOp::Ne => "!=",
                    BinaryOp::Gt => ">",
                    BinaryOp::Lt => "<",
                    BinaryOp::Ge => ">=",
                    BinaryOp::Le => "<=",
                    BinaryOp::And => "and",
                    BinaryOp::Or => "or",
                };
                // Remove unnecessary parentheses for cleaner code
                Ok(format!("{} {} {}", left_str, op_str, right_str))
            }
            ExprKind::Unary(op, inner) => {
                let inner_str = self.generate_expr(inner)?;
                let op_str = match op {
                    UnaryOp::Neg => "-",
                    UnaryOp::Not => "!",
                    UnaryOp::Deref => ".*",
                };
                if *op == UnaryOp::Deref {
                    Ok(format!("({}{})", op_str, inner_str))
                } else {
                    Ok(format!("({}{})", op_str, inner_str))
                }
            }
            ExprKind::Call(func, args) => {
                let func_str = self.generate_expr(func)?;
                let args_str: Vec<String> = args
                    .iter()
                    .map(|a| self.generate_expr(a))
                    .collect::<Result<Vec<_>, _>>()?;

                // Check if this is a Timer method call (obj.method())
                if func_str.contains(".start") {
                    let obj = func_str.replace(".start", "");
                    return Ok(format!("{}.start()", obj));
                }
                if func_str.contains(".stop") {
                    let obj = func_str.replace(".stop", "");
                    return Ok(format!("{}.stop()", obj));
                }
                if func_str.contains(".getTime") {
                    let obj = func_str.replace(".getTime", "");
                    if args_str.is_empty() {
                        return Ok(format!("{}.getTime(\"ms\")", obj));
                    } else {
                        return Ok(format!("{}.getTime({})", obj, args_str.join(", ")));
                    }
                }

                // Handle built-in functions
                let zig_func = match func_str.as_str() {
                    "print" => "print".to_string(), // Use our optimized print helper
                    "input" => "input".to_string(),
                    "len" => "@as(usize, 0)".to_string(),
                    "sleep" => "std.time.sleep".to_string(),
                    _ => func_str,
                };

                // Handle input() - supports:
                // 1. input() - no prompt, returns string
                // 2. input("prompt") - with prompt, returns string
                // 3. input("prompt {}", arg1, ...) - with formatted prompt, returns string
                // 4. input("prompt {}", var) - as statement, reads input into var with type conversion
                if zig_func == "input" {
                    if args_str.is_empty() {
                        // No arguments - just read input (returns string)
                        Ok("readInput()".to_string())
                    } else if args_str.len() == 1 {
                        // Single argument - prompt string
                        let prompt = &args_str[0];
                        if prompt.starts_with('"') {
                            // Check if it has format placeholders
                            if prompt.contains("{}") || prompt.contains("{var}") {
                                // Has format placeholders but no values - treat as plain prompt
                                Ok(format!("readInputWithPrompt({}, .{{}})", prompt))
                            } else {
                                // Plain prompt string
                                Ok(format!("readInputWithPrompt(\"{{}}\", .{{ {} }})", prompt))
                            }
                        } else {
                            // Variable as prompt - this is input("prompt", var) pattern
                            // Read input and convert to variable's type
                            Ok(format!("readInputTo(\"{{}}\", .{{}}, @TypeOf({}))", prompt))
                        }
                    } else {
                        // Multiple arguments - first is format string, rest are values/variables
                        let format_str = &args_str[0];
                        let last_arg = args_str.last().unwrap();
                        
                        // Check if last argument is a variable (not a string literal)
                        // This indicates input("prompt {}", var) pattern for type conversion
                        if !last_arg.starts_with('"') && !last_arg.starts_with('&') {
                            // This is input("prompt {}", var) pattern - read into variable with type conversion
                            let values = if args_str.len() > 2 {
                                // Multiple format values before the target variable
                                args_str[1..args_str.len()-1].join(", ")
                            } else {
                                String::new()
                            };
                            let target_var = last_arg;
                            if values.is_empty() {
                                Ok(format!("readInputTo({}, .{{}}, @TypeOf({}))", format_str, target_var))
                            } else {
                                Ok(format!("readInputTo({}, .{{ {} }}, @TypeOf({}))", format_str, values, target_var))
                            }
                        } else {
                            // All arguments are format values - returns string
                            let values = args_str[1..].join(", ");
                            Ok(format!("readInputWithPrompt({}, .{{ {} }})", format_str, values))
                        }
                    }
                }
                // Optimized print handling
                else if zig_func == "print" {
                    if args_str.is_empty() {
                        Ok("print(\"\\n\", .{})".to_string())
                    } else if args_str.len() == 1 {
                        let first_arg = &args_str[0];
                        // String with format placeholders - need to convert {var} to {}
                        if first_arg.starts_with('"') {
                            self.convert_print_format(first_arg)
                        } else {
                            // Single non-string argument - direct print
                            Ok(format!("print(\"{{}}\", .{{ {} }})", first_arg))
                        }
                    } else {
                        // Multiple arguments - first is format string, rest are values
                        let format_str = &args_str[0];
                        let values = args_str[1..].join(", ");
                        Ok(format!("print({}, .{{ {} }})", format_str, values))
                    }
                } else if zig_func == "std.time.sleep" {
                    // Convert milliseconds to nanoseconds for Zig
                    if let Some(arg) = args_str.first() {
                        Ok(format!("{}(@as(u64, {}) * 1_000_000)", zig_func, arg))
                    } else {
                        Ok(format!("{}(0)", zig_func))
                    }
                } else {
                    Ok(format!("{}({})", zig_func, args_str.join(", ")))
                }
            }
            ExprKind::FieldAccess(obj, field) => {
                let obj_str = self.generate_expr(obj)?;
                Ok(format!("{}.{}", obj_str, field))
            }
            ExprKind::Array(elements) => {
                let elems_str: Vec<String> = elements
                    .iter()
                    .map(|e| self.generate_expr(e))
                    .collect::<Result<Vec<_>, _>>()?;
                Ok(format!("[_]{{{{ {} }}}}", elems_str.join(", ")))
            }
            ExprKind::ArrayIndex(arr, index) => {
                let arr_str = self.generate_expr(arr)?;
                let index_str = self.generate_expr(index)?;
                Ok(format!("{}[{}]", arr_str, index_str))
            }
            ExprKind::Block(_block) => {
                // Inline block - generate inline
                Ok("{ /* block */ }".to_string())
            }
            ExprKind::AsyncBlock(_block) => Ok("{ /* async block */ }".to_string()),
            ExprKind::TryBlock(_block) => Ok("{}".to_string()),
            ExprKind::Cast(inner, target_type) => {
                let inner_str = self.generate_expr(inner)?;
                let zig_type = target_type.to_zig_type();
                Ok(format!("@as({}, {})", zig_type, inner_str))
            }
            ExprKind::MemoryCast(cast_type, inner) => {
                let inner_str = self.generate_expr(inner)?;
                let zig_type = cast_type.to_zig_type();
                Ok(format!("@as({}, @bitCast({}))", zig_type, inner_str))
            }
        }
    }

    fn generate_literal(&self, lit: &Literal) -> CodeGenResult<String> {
        match lit {
            Literal::Int(s) => Ok(s.clone()),
            Literal::Float(s) => Ok(s.clone()),
            Literal::String(s) => {
                // Escape special characters for Zig
                let escaped = s
                    .replace('\\', "\\\\")
                    .replace('\n', "\\n")
                    .replace('\r', "\\r")
                    .replace('\t', "\\t")
                    .replace('"', "\\\"");
                Ok(format!("\"{}\"", escaped))
            }
            Literal::InterpolatedString(s) => {
                // Escape special characters for Zig
                let escaped = s
                    .replace('\\', "\\\\")
                    .replace('\n', "\\n")
                    .replace('\r', "\\r")
                    .replace('\t', "\\t")
                    .replace('"', "\\\"");
                Ok(format!("\"{}\"", escaped))
            }
            Literal::Bool(b) => Ok(if *b { "true" } else { "false" }.to_string()),
        }
    }

    fn writeln(&mut self, line: &str) {
        for _ in 0..self.indent_level {
            self.output.push_str("    ");
        }
        self.output.push_str(line);
        self.output.push('\n');
    }

    /// Optimized print format conversion - converts CatLang {var} to Zig {}
    /// Note: The input string is already escaped by generate_literal
    fn convert_print_format(&self, format_str: &str) -> Result<String, CodeGenError> {
        let mut result = String::with_capacity(format_str.len());
        let mut vars = Vec::new();

        // Skip opening and closing quotes
        let content = format_str.trim_start_matches('"').trim_end_matches('"');

        let mut i = 0;
        while i < content.len() {
            if content[i..].starts_with('{') {
                // Check for escaped {{
                if i + 1 < content.len() && content[i + 1..].starts_with('{') {
                    result.push('{');
                    i += 2;
                    continue;
                }

                // Find closing }
                if let Some(end) = content[i..].find('}') {
                    let var_name = &content[i + 1..i + end];
                    if !var_name.is_empty() {
                        vars.push(var_name.to_string());
                        result.push_str("{}");
                        i += end + 1;
                        continue;
                    }
                }
            }

            if i < content.len() {
                let ch = content.as_bytes()[i] as char;
                result.push(ch);
                i += 1;
            }
        }

        if vars.is_empty() {
            Ok(format!("print(\"{}\", .{{}})", result))
        } else {
            Ok(format!("print(\"{}\", .{{ {} }})", result, vars.join(", ")))
        }
    }

    fn ends_with_return(&self) -> bool {
        self.output.trim_end().ends_with("return;") || self.output.trim_end().ends_with('}')
    }
}

/// Public function to generate Zig code from AST
pub fn generate_zig(program: &Program) -> CodeGenResult<String> {
    ZigCodeGen::new().generate(program)
}
